name: Auto Commit Changes

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main
  workflow_dispatch: 

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Linter and Format Code
        run: |
          npm run lint --fix
          npm run format -- --write

      - name: Verify Code Changes
        run: |
          git diff --exit-code || echo "Changes detected"  # Checks for changes in the repository

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git status  # To verify changes before committing
          git commit -m "chore: auto commit changes via GitHub Actions" || echo "No changes to commit"
          git push
